config/routes.rb
Pairedwithus::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end

  resources :pairing_session_notes

  resources :pairing_sessions

  root to: "PairingSessions#index"

end

app/models/pairing_session.rb
class PairingSession < ActiveRecord::Base
  belongs_to :pair_1, :foreign_key => :pair_1_id, :class_name => "User"
  belongs_to :pair_2, :foreign_key => :pair_2_id, :class_name => "User"
  has_many :notes, :class_name => "PairingSessionNote"

  def self.with_users
    includes(:pair_1, :pair_2)
  end

  def participants
    [pair_1, pair_2]
  end
end

app/models/pairing_session_note.rb
class PairingSessionNote < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  include Gravtastic
  is_gravtastic secure: false, size: 80, default: "identicon"

  devise :trackable, :token_authenticatable, :omniauthable

  has_many :pairing_sessions_left, foreign_key: :pair_1_id, class_name: "PairingSession"
  has_many :pairing_sessions_right, foreign_key: :pair_2_id, class_name: "PairingSession"

  def pairing_sessions
    (pairing_sessions_left + pairing_sessions_right).sort_by(&:start).reverse
  end

  def new_pairing_session(params = {})
    pairing_sessions_left.new params
  end

  def find_pairing_session(id)
    PairingSession.where("id = ? AND (pair_1_id = ? OR pair_2_id = ?)",
                          id, self.id, self.id).first
  end

  def self.find_for_facebook_oauth(access_token, signed_in_resource=nil)
    data = access_token['extra']['user_hash']
    if user = User.find_by_email(data["email"])
      user
    else # Create a user with a stub password.
      User.create(:email => data["email"], :password => Devise.friendly_token[0,20])
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["user_hash"]
        user.email = data["email"]
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pairing_session_notes_controller.rb
class PairingSessionNotesController < ApplicationController
end

app/controllers/pairing_sessions_controller.rb
class PairingSessionsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @sessions = current_user.pairing_sessions
  end

  def show
    @session = current_user.find_pairing_session(params[:id])
  end

  def new
    @session = current_user.new_pairing_session
  end

  def create
    @session = current_user.new_pairing_session params[:pairing_session]
    if @session.save
      redirect_to pairing_sessions_url, notice: "Pairing session successfully registered"
    else
      render :new
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model
    @user = User.find_for_facebook_oauth(env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.facebook_data"] = env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def passthru
    render :file => "#{Rails.root}/public/404.html", :status => 404, :layout => false
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pairing_session_notes_helper.rb
module PairingSessionNotesHelper
end

app/helpers/pairing_sessions_helper.rb
module PairingSessionsHelper
  def pairs_for_select(without = [current_user])
    (User.all - without).map { |user|
      [user.name, user.id]
    }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PairedWith.Us</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application", :debug => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header>
    <h1><%= link_to "Paired With Us", root_path %></h1>
    <nav>
      <ul>
        <% if user_signed_in? %>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% end %>
      </ul>
    </nav>
    <% if user_signed_in? %>
      <section class='user_info'>
        <%= current_user.email %>
      </section>
    <% end %>
  </header>
  <section id='content'>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </section>
  <aside>
  <nav>
    <ul>
      <li><%= link_to "Register A Pairing Session", new_pairing_session_path %></li>
    </ul>
  </nav>
  </section>


</body>
</html>

app/views/pairing_sessions/index.html.haml
%script{:type => "text/template", :id => "pairing-session-template"}
  %li.session
    %article.information
      .date-as-calendar
        .month <%=date.month%>
        .day <%=date.day%>
    %ul.participants.box
      %li
        .name <%=pair_1.name%>
        .image
          <img src=<%=pair_1.gravatar_url%>></img>
      %li
        .name <%=pair_2.name%>
        .image
          <img src=<%=pair_2.gravatar_url%>></img>


.box#session-listing
  %header
    %h1 Pairing Sessions
  %section.detail
    %ul.sessions

= javascript_include_tag "pairing_session_index", debug: true

:javascript
  function build_session(day, month, year, pair_1_name, pair_1_gravatar_url,
              pair_2_name, pair_2_gravatar_url) {
    return {
      date: {
        day: day,
        month: month,
        year: year
      },

      pair_1: {
        name: pair_1_name,
        gravatar_url: pair_1_gravatar_url
      },

      pair_2: {
        name: pair_2_name,
        gravatar_url: pair_2_gravatar_url
      }
    };
  }

%script
  $(function() {
  - @sessions.each do |session|
    ==window.pairing_sessions.add(build_session("#{session.start.strftime('%e')}","#{session.start.strftime('%b')}","#{session.start.strftime('%Y')}","#{session.participants.first.name}", "#{session.participants.first.gravatar_url}", "#{session.participants.last.name}","#{session.participants.last.gravatar_url}"));
  });

app/views/pairing_sessions/new.html.haml
.box
  %h1 Please register your pairing session
  .detail
    = form_for @session , html: {class: "madlib_form"} do |f|
      %p
        I paired with
        = f.select :pair_2_id, pairs_for_select
        on
        = f.text_field :start, class: "date-picker"
        for
        = f.text_field :duration
        hours.
      = f.submit "Register this pairing session"

app/views/pairing_sessions/show.html.haml
.box.session_listing
  %h1 What a great pairing session
  .session
    .information
      .date_as_calendar
        .month=@session.start.strftime("%b")
        .day=@session.start.strftime("%e")
    %ul.participants.box
      -@session.participants.each do |participant|
        %li
          .name=participant.name
          =image_tag participant.gravatar_url, class: "gravatar"